conf/authdata.json
conf/config.joi.js
conf/config.json
extensions/replication/queueProcessor/QueueProcessor.js
extensions/replication/utils/QueueEntry.js
lib/clients/backbeat-2017-07-01.api.json

- set the destination owner ID and display name in metadata before
putting to the destination
- transmit the owner ID in the 'x-scal-canonical-id' header when
putting data
- parse the comma-separated source and destination roles from bucket
replication configuration
- use an abstraction to handle authentication for 'account' and
'role' auth types. For account type, match the configured local
user with the role ARN read in the bucket replication
configuration.
- rename auth types to 'user' or 'role' for local user (or account)
authentication or role-based.

Various fixes for MVP

---

package.json

it seems to be needed at runtime not only for dev

fix aws sdk dependency in package.json

---

conf/config.joi.js
conf/config.json
extensions/replication/queuePopulator/QueuePopulator.js
extensions/replication/queuePopulator/task.js
extensions/replication/queueProcessor/QueueProcessor.js
lib/BackbeatConsumer.js
lib/BackbeatProducer.js
lib/config/configItems.joi.js
tests/behavior/extensions/replication/queuePopulator.js
tests/functional/BackbeatConsumer.js
tests/functional/BackbeatProducer.js

In the backbeat config, zookeeper is configured with the whole
endpoint string "host:port/chroot" instead of separate fields. This
will ease integration with Federation.
Also do various other config cleanups:
- changed name of zookeeperNamespace to zookeeperPath
- moved 'groupId' config value to 'queueProcessor' config section
- explicitly provide the source configuration object to queue populator
- Add JSDoc to queue processor constructor

cleanup: configure zookeeper endpoint as a string

---

extensions/replication/queueProcessor/QueueProcessor.js

This will allow to re-use a pool of connections both for the source
requests and the destination requests.
To do this we simply setup two global HTTP agents, one for the source
and one for the destination, and attach them when creating the AWS
client object.
For SSL support we will need an HTTPS agent instead.
Tested manually by spawning an ad-hoc server with 'nc' on the
destination.

ft: enable keep-alive mode for backbeat AWS client

---

extensions/replication/queuePopulator/QueuePopulator.js
extensions/replication/queueProcessor/QueueProcessor.js

Instead of calling newRequestLogger() once for the lifetime of the
queue populator, only create the Logger object once, and create a new
request logger object for every entry processed from Kafka.
This enables to keep track of logs more easily for each processed
entry, and more importantly, shall fix an issue that @ThibaultRiviere
mentioned in another PR, which is that a request logger keeps every
log in memory in order to dump all logs when an error occurs. For the
queue processor, it would mean exhausting memory eventually with a
single long-lived request logger object.

bf: call newRequestLogger() for every entry to process

---

conf/config.joi.js
conf/config.json
extensions/replication/queuePopulator/BucketFileLogReader.js
extensions/replication/queuePopulator/LogReader.js
extensions/replication/queuePopulator/QueuePopulator.js
extensions/replication/queuePopulator/RaftLogReader.js
extensions/replication/queuePopulator/task.js
tests/behavior/extensions/replication/queuePopulator.js
tests/config.json

Follow-up of https://github.com/scality/backbeat/pull/23.
Use the ProvisionDispatcher class to configure the queue populator so that it manages one or more raft session IDs. Make it dynamic so that a running queue populator can switch to another set of raft session
IDs any time (if the dispatcher reassigns a new one, after a failure for example), or can become idle as well if no raft ID is assigned from zookeeper.
Add support for graceful handling of SIGTERM, to unsubscribe from the dispatcher so that the dispatcher can quickly notify other queue populators to take over the unmanaged raft IDs.

Integrate ProvisionDispatcher class in queue populator

---

extensions/replication/queuePopulator/QueuePopulator.js
extensions/replication/queuePopulator/task.js

Don't return ServiceUnavailable in this case, return a success with an empty
array of results

bf: fix error when populator has no log source

---

extensions/replication/queueProcessor/QueueProcessor.js
package.json

Split error management in two categories: retryable and permanent
failures. The choice is currently based on the 'retryable' field of
the error sent back by the AWS SDK, but it could be refined later.
- retryable errors get retried indefinitely with an exponential
back-off algorithm (using 'backo' open-source module, it's simple
but non-trivial to do properly so makes sense to use a third-party
module IMO). We may later think about giving up after some (long
enough) time without success and set the replication status to
FAILED, not sure we want to though, if the errors are really
retryable they should eventually succeed.
- permanent errors lead to the status FAILED being written on the
source object version.
- failures to write the replication status also lead to retries.
Tests should be …

enhance replication error management

---

conf/config.joi.js
conf/config.json
extensions/replication/queueProcessor/QueueProcessor.js
lib/config/configItems.joi.js
tests/config.json
tests/functional/replication/queueProcessor.js

For now, only the first element of the list is used, this will allow
to update Federation to provide a list of hosts in the meantime, later
we will refine to actually use multiple hosts from the list.
For source it does not matter but some of the code shares processing
of host/port from conf, so it makes more sense to have both source and
destination use the same convention in config.

ft: use a bootstrap list for source/target S3 and Vault

---

credentials/CredentialsManager.js

This so that AWS client does not touch the original global arsenal error.

bf: ensure we generate new errors in CredentialsManager

---

conf/config.joi.js
conf/config.json
extensions/replication/queueProcessor/QueueProcessor.js

Now, retries are disabled in AWS clients, instead each step is retried individually depending on the retry policy.
The general idea is to manage retries ourselves (I heard some people are uncomfortable with AWS retry behavior), it also improves the situation especially with MPU, where a single part put failure would have retried the whole MPU operation. On flaky networks this could have led to diverging and eventually failing to replicate data.
Note: based on PR https://github.com/scality/backbeat/pull/15

update retry strategy

---

tests/functional/replication/queueProcessor.js
tests/utils/TestConfigurator.js

Note: based on PR https://github.com/scality/backbeat/pull/31
- refactor of the existing success path tests using the TestConfigurator class
- new error handling tests with various error cases mocked

test: new QueueProcessor error management tests

---

lib/clients/backbeat-2017-07-01.api.json
tests/functional/replication/queueProcessor.js

This commit updates the Backbeat S3 routes to match new format which
gives flexibility over the admin namespace on S3.

ft: update backbeat S3 routes

---

circle.yml

Oops, please see following comment for reference:
https://github.com/scality/backbeat/pull/36#issuecomment-320962020
Also following @alexandre-merle advice, removing node_modules and reinstalling

fix: g++ syntax for circleci

---

lib/BackbeatProducer.js

Since errors may occur at any time, especially at startup when kafka
is not yet listening, we should not reset the _ready flag which is
initially set to true when zookeeper is up and running on port 2181
and could return kafka's configuration with success, even though port
9092 is not yet ready.
We observed a backtrace saying 'producer is not ready yet' in a loop
on the queue populator, which required restarting the container, we
suspect that this is the cause but haven't confirmed yet. In any case
this fixes a real bug that may happen in other cases of errors.

bf: no reset of '_ready' flag on producer error

---

credentials/CredentialsManager.js
extensions/replication/queueProcessor/QueueProcessor.js
tests/unit/CredentialsManager.js

Note: based on PR https://github.com/scality/backbeat/pull/66.
- request uids forwarding: backbeat queue processor now sends the
request uids for the current processed entry to S3 and Vault
routes, through a custom X-Scal-Request-Uids header.
- call log.end() when done processing an entry, so that elapsed time
is logged
- modify 'retryTotalTime' to 'retryTotalMs' logged value when giving
up retries, to be consistent with 'elapsed_ms' format

S3C-781 logging enhancements

---

circle.yml
tests/functional/ProvisionDispatcher.spec.js

+ disable provisioning functional tests
They don't pass on the CI, for some known and unknown reasons, it will
require significant time to investigate and fix, so disabling them for now
since the rest of the ft_test suite should be integrated anyway.

test: add 'npm run ft_test' rule to circle.yml

---

README.md

This guide is intended to help users get started with using backbeat's replication extension. It uses Vault (a private repository), so it is primarily targeted for internal usage at Scality. However, getting kafka and zookeeper running and configured would allow users to quickly develop by reusing backbeat's consumer and producer classes. 
From here, we might consider adding guides for running zookeeper and kafka with docker (with spotfy/kafka, and evenutally Scality's container). Also, a guide for other OS is in order. 😄

FT: Add backbeat local quickstart guide

---

extensions/replication/queueProcessor/QueueProcessor.js
extensions/replication/utils/QueueEntry.js
tests/functional/replication/queueProcessor.js

This call was not decoding a previously encoded value, only the kafka
record key was encoded, not the key stored in the queue entry JSON.
Also fix how 404 errors are detected on the source side (if the source object
does not exist): S3 client does not necessarily return a proper ObjNotFound
code, so just check for 404 HTTP code.

bf: remove decodeURIComponent() in QueueEntry

---

conf/config.joi.js
conf/config.json
extensions/replication/queuePopulator/QueuePopulator.js
extensions/replication/queueProcessor/QueueProcessor.js
lib/clients/zookeeper.js

Auto-create queue populator base path on zookeeper if it does not
exist, when starting up the queue populator deployed previously with
docker swarm for zenko.
Since docker and docker swarm do not provide an easy way to run
specific commands at deployment time, especially conditioned to
containers being up and running first, in order to ensure zookeeper
base paths are created initially, we wrap the zookeeper client handle
creation with some custom code to do this.
This is enabled only in zenko mode with docker swarm deployment,
default options (including Federation-based deployment) do not change
the existing behavior which is to not create the base path if it does
not exist (and then further zookeeper commands shall fail with NO_NODE
errors).

ft: auto-create zookeeper base path for zenko

---

extensions/replication/queueProcessor/QueueProcessor.js

Use port 80 when not specified in bootstrap list items for backbeat target.
Depends on Arsenal PR https://github.com/scality/Arsenal/pull/332

use default port 80 in round-robin

---

extensions/replication/queuePopulator/LogReader.js
lib/BackbeatProducer.js

The kafka-node API was misused, resulting in keyed partitioning being
not used: the key has to be part of the individual payload items, not
the 'messages' list. Also fix the provided key to include the bucket
name (may lead to slightly better dispersion across partitions).

bf: fix use of keyed partitioning

---

extensions/replication/queueProcessor/QueueProcessorTask.js

Do not process entries and log a warning if no target site is
configured (no bootstrap list), instead of aborting with an
exception.
Also set the replication status to FAILED.

ft: skip entry if target site not configured

---

extensions/replication/queueProcessor/MultipleBackendTask.js
extensions/replication/queueProcessor/QueueProcessor.js
extensions/replication/queueProcessor/QueueProcessorTask.js
extensions/replication/utils/QueueEntry.js
extensions/replication/utils/attachReqUids.js
lib/clients/backbeat-2017-07-01.api.json

Depends on https://github.com/scality/S3/pull/935.
Handles replication of single-part objects to AWS.
Forthcoming replication operation support:
* MPU objects
* Metadata-only operations (zero-byte objects, putting object tagging, etc.)
* Object deletion

FT: Add task to replicate data to AWS

---

extensions/replication/queueProcessor/QueueProcessor.js
extensions/replication/queueProcessor/ReplicationTaskScheduler.js
tests/unit/replication/ReplicationTaskScheduler.spec.js

Ensure serialization of operations at object level instead of for
every version of the object, so that the ordering guarantees are valid
for AWS backend as well.

ft: serialize all ops on object

---

extensions/replication/queueProcessor/QueueProcessorTask.js
extensions/replication/utils/QueueEntry.js
tests/functional/replication/queueProcessor.js
tests/unit/replication/QueueEntry.spec.js

Depends on Arsenal PR https://github.com/scality/Arsenal/pull/326
cleanup: use ObjectMD class for QueueEntry helper
Since QueueEntry is essentially holding metadata from the entry, plus
a few additional info, make it inherit from ObjectMD so we get access
to all its getters/setters directly.
Also use ObjectMDLocation class to manipulate location info.
Most helpers removed from QueueEntry have been moved to Arsenal ObjectMD/ObjectMDLocation.

use ObjectMD class

---

README.md
conf/config.json
docs/crr-to-aws-s3.md
lib/config/configItems.joi.js
tests/unit/conf/Config.js

With this commit, bootstrapList expects the endpoint to have site/type or site/servers combination. Currently the only allowed type is aws_s3.

ft: support for aws-s3 replication endpoint

---

extensions/replication/queueProcessor/QueueProcessor.js

When fetching locations, don't modify the original array of locations
when constructing the reduced locations array, to not induce
side-effects when reusing the original array (e.g to fetch the same
reduced locations again for another get/put cycle).
7.1 fix only, no need for forward port as master has a different
implementation and is not affected.

bf: don't overwrite part size in locations

---

extensions/replication/queueProcessor/MultipleBackendTask.js

On retry during an error we do not want to use the round robin `pickNextHost` method since `destHosts` is not set in a configuration to replicate to AWS.
See: https://github.com/scality/backbeat/blob/master/extensions/replication/queueProcessor/QueueProcessorTask.js#L157

FIX: Update all error origins for AWS task

---

lib/BackbeatConsumer.js

It's not necessary to pause the consumer when the Kafka client returns
errors, and it may block the consumption for no good reason, so better
remove it.

bf: remove pause() call on Kafka errors

---

package.json

Version 1.6.x has issues refreshing the brokers leader map when
connectivity is lost with brokers. Version 2.2 has fixes that seem
to solve those problems.

bf: upgrade kafka node to 2.2.x

---

extensions/replication/queueProcessor/MultipleBackendTask.js
lib/clients/backbeat-2017-07-01.api.json

Depends on https://github.com/scality/S3/pull/1010.
Object tagging operations that are made before the source object has completed replication do not have the `datastoreVersionId` in the Kafka entry. 
Because all operations for the multiple backend are serialized, when any tagging operation is being replicated we can guarantee that the source object's metadata will have been updated at this point. Hence we send the source bucket and source version ID for cloud server to retrieve the information before making the request to an external location. Also, we can eliminate a GET request for the source object's tags because they are already available in the Kafka entry.

FIX: Source should get destination version for AWS

---

credentials/CredentialsManager.js
tests/functional/replication/queueProcessor.js

Set the 'retryable' field in the errors generated from
CredentialsManager.refresh() when relevant, to be in sync with AWS SDK
behavior, which is also how the calling code of the SDK checks whether
it should retry the request.
The criteria are when the error is an InternalError or
ServiceUnavailble we retry, otherwise we don't.

bf: allow retries on errors in CredentialsManager.refresh()

---

credentials/CredentialsManager.js

There is another case of missing retry in credentials refresh, when
the error code itself is 500: support retries when the error code
field is numeric 500 or 503.
Here's the log trace in backbeat processor seen during tests which did not trigger a retry:
```
/opt/logs/scality-backbeat/logs/processor-2-0.log:{"name":"Backbeat:Replication:QueueProcessor","method":"QueueProcessor._setupRoles","entry":{"bucket":"jonathan-bucket1","objectKey":"CF00","versionId":"98487475265477999999RG001  80.133153.93","isDeleteMarker":false},"origin":"source","peer":{"host":"localhost","port":8000},"error":"Missing credentials in config","time":1512524767177,"req_id":"b984c939d54da6041f25","level":"error","message":"error getting replication configuration from S3","hostname":"s3-node-na-0.novalocal","pid":39} …
```

bf: credentials refresh missing retry

---

docs/site-level-crr.md

Add a document explaining how site-level CRR (echo) works, how to
enable it and which steps are needed in case of failover.

doc: site-level CRR

---

extensions/replication/tasks/ReplicateObject.js
lib/clients/backbeat-2017-07-01.api.json
tests/functional/replication/queueProcessor.js

With the introduction of one to many crr, there will be a status update for each backend.
Since there will be multiple requests to the source to update the replication status, it's important
to get the latest copy of the metadata blob as previous updates would render the copy it's holding stale.

ft: support for get and put metadata blob

---

lib/queuePopulator/LogReader.js
lib/queuePopulator/QueuePopulatorExtension.js

Call QueuePopulatorExtension.setBatch() every time new entries are received,
because multiple readers can be intermingled sending their respective data,
and although the LogReader class is managing a single reader, the extensions
`batch` field is global to all readers, so it has to be set every time.
Note that this fix is only required with streamed log reader (i.e. with https://github.com/scality/bucketclient/pull/126 and https://github.com/scality/Arsenal/pull/379)

bf: fix concurrency issue with log reader

---

conf/config.joi.js
conf/config.json
extensions/lifecycle/LifecycleConfigValidator.js
extensions/lifecycle/index.js

Add config params related to lifecycle components: kafka topics, conductor,
producer, consumer, and rule-specific config (expiration...).

ft: update config with lifecycle params

---

extensions/replication/utils/SetupReplication.js

This bug was reported in the BETA 7.2.0.4-rc2 build. I am assuming the tag is created from the rel/7.4 branch (hence the target here) since this change does not exist in rel/7.2.

FIX: Update replication setup script

---

lib/BackbeatProducer.js

Allow the possibility to use non-keyed partitioning without specifying
a partition number, so that the default partitioning scheme is used
to spread messages across partitions without providing a key.

non-keyed partitioner in BackbeatProducer

---

bin/queuePopulator.js
extensions/replication/constants.js
lib/MetricsConsumer.js
lib/queuePopulator/BucketFileLogReader.js
lib/queuePopulator/QueuePopulator.js

This PR is focused on consuming the metrics from Kafka and storing to Redis.
These Redis metric keys will be exposed by the Backbeat Server/API (#102) through to-be-built routes.

ft: add metrics consumer

---

conf/config.json
extensions/lifecycle/LifecycleConfigValidator.js
extensions/lifecycle/lifecycleProducer/LifecycleProducer.js
extensions/lifecycle/tasks/LifecycleTask.js
lib/BackbeatConsumer.js
tests/config.json
tests/unit/lifecycle/LifecycleTask.spec.js
tests/utils/Rule.js

Lifecycle Tasks handles the AWS operations for validating and matching rules. These tasks are processed via the Lifecycle Producer. 
Please refer to the Lifecycle design docs to view the LifecycleProducer/LifecycleTask operations.
To be added and in the works are adding functional tests for specifically LifecycleTask class

ft: add lifecycle producer task

---

circle.yml
index.js
lib/BackbeatProducer.js
lib/api/BackbeatAPI.js
lib/api/BackbeatRequest.js
lib/api/BackbeatServer.js
lib/api/routes.js
package.json
tests/config.json
tests/functional/api/BackbeatServer.js
tests/utils/wait_for_local_port.bash

Add `/_/healthcheck` route
In order to run the server, it is required to run zookeeper and kafka
NOTE: This PR is still using the SOHU-Co/kafka-node module
Sample output:
`
[{"0":{"nodeId":0,"host":"na-node1","port":9092},"1":{"nodeId":1,"host":"na-node2","port":9092},"2":{"nodeId":2,"host":"na-node3","port":9092},"3":{"nodeId":3,"host":"na-node4","port":9092},"4":{"nodeId":4,"host":"na-node5","port":9092}},{"metadata":{"0":{"topic":"backbeat-replication","partition":0,"leader":4,"replicas":[0,1,4],"isr":[1,4,0]},"1":{"topic":"backbeat-replication","partition":1,"leader":1,"replicas":[0,1,2],"isr":[1,2,0]},"2":{"topic":"backbeat-replication","partition":2,"leader":1,"replicas":[1,2,3],"isr":[1,2,3]},"3":{"topic":"backbeat-replication","partition":3,"leader":2,"replicas":[2,3,4],"isr":[3,2, …

ft: Add backbeat api route healthcheck

---

conf/config.json
extensions/lifecycle/LifecycleConfigValidator.js
extensions/lifecycle/conductor/LifecycleConductor.js
extensions/lifecycle/conductor/service.js
extensions/replication/replicationStatusProcessor/ReplicationStatusProcessor.js
lib/BackbeatConsumer.js
lib/BackbeatProducer.js
lib/clients/zookeeper.js
package.json
tests/functional/lifecycle/LifecycleConductor.spec.js
tests/functional/replication/queueProcessor.js
tests/functional/utils/BackbeatTestConsumer.spec.js
tests/utils/BackbeatTestConsumer.js

Implement the conductor piece of lifecycle, which reads the list of lifecycled buckets in zookeeper, and populates tasks in kafka to start listing those buckets.
I advise to review one commit at a time.

lifecycle conductor

---

lib/queuePopulator/BucketFileLogReader.js
lib/queuePopulator/RaftLogReader.js

`index.js` was updated in Arsenal, which slightly changed the import format for the metadata files.
causing issues in Integration

bf: update Arsenal imports ZENKO-140

---

extensions/lifecycle/conductor/LifecycleConductor.js
extensions/lifecycle/lifecycleConsumer/LifecycleConsumer.js
extensions/lifecycle/lifecycleProducer/LifecycleProducer.js
extensions/lifecycle/tasks/LifecycleObjectTask.js
extensions/lifecycle/tasks/LifecycleTask.js
tests/functional/lifecycle/LifecycleConductor.spec.js

The issue with the current design is that we only send one
'unlockBucket' message after the bucket has been listed entirely, but
nothing guarantees that previous listing tasks executed by other
producers will not be longer to proceed, effectively voiding the
purpose of knowing when all objects of this bucket have been
processed.
One case where this is very likely to happen is when a specific range
of objects in the bucket have to be expired at once (other than the
last listed range), because it will take longer to process objects for
that particular range than it will be to finish listing the bucket and
processing the expirations for last range. Moreover this is a common
case in production (e.g. expiring a sub-directory).
An alternative implementation based on monitoring the backlog of …

remove broken design with unlockBucket messages

---

extensions/lifecycle/LifecycleConfigValidator.js

The producer can be aggressive with 10 concurrent operations, since
each of them can generate in turn 10 HEAD requests to S3 server (and
there can be 5 concurrent producers on the system), this shows high
CPU usage. Reducing the concurrency should make lifecycle processing
less agressive on resources.

bf: set default concurrency of bucket processing to 1

---

conf/config.json
extensions/lifecycle/LifecycleConfigValidator.js
extensions/lifecycle/conductor/LifecycleConductor.js
extensions/lifecycle/lifecycleConsumer/LifecycleConsumer.js
extensions/lifecycle/lifecycleProducer/LifecycleProducer.js
lib/BackbeatConsumer.js
lib/clients/zookeeper.js
tests/functional/BackbeatConsumer.js
tests/functional/lifecycle/LifecycleConductor.spec.js

* bf: add backlog metrics to BackbeatConsumer
Now BackbeatConsumer will publish metrics periodically in zookeeper
about the current backlog: consumer offset and latest topic
offset. This will be used to check how much is the backlog (or if
there is any at all) and throttle processing if needed.
* bf: backpressure for lifecycle
In order to avoid accumulating lifecycle tasks and diverging when the
system cannot process everything in the allocated time, add a
mechanism to skip processing cycles when the previous cycle has not
finished yet.
Kafka consumers in LifecycleConsumer and LifecycleProducer now publish
to zookeeper, for their consumed topic partitions, their current
committed offset and the latest topic partition offset.
The conductor checks those when he's about to start a new cycle: …

bf: rework backpressure

---

lib/MetricsConsumer.js
lib/api/BackbeatAPI.js
lib/models/StatsModel.js
tests/functional/api/BackbeatServer.js

StatsClient normalized time by seconds. Since we want to use
intervals by a default of 5 minutes (or configurable to be higher),
we want to normalize time by minutes.
Please only review 877feceb10d9f16cd38b1b4454cfa10d288b048b

bf: statsmodel intervals

---

conf/Config.js
extensions/replication/ReplicationQueuePopulator.js
extensions/replication/queueProcessor/QueueProcessor.js
extensions/replication/utils/ObjectQueueEntry.js
lib/BackbeatConsumer.js
lib/MetricsProducer.js
lib/api/BackbeatAPI.js
lib/api/BackbeatRequest.js
lib/api/BackbeatServer.js
lib/api/routes.js
lib/models/MetricsModel.js
lib/queuePopulator/LogReader.js
lib/queuePopulator/QueuePopulator.js
lib/queuePopulator/QueuePopulatorExtension.js
tests/functional/api/BackbeatServer.js

Metric routes have been changed to the following format:
`/_/metrics/<extension>/<site>`
or you can add an optional metric type (i.e. backlog, completions, throughput):
`/_/metrics/<extension>/<site>/<type>`
Where `<site>` === the cloud type (i.e. `aws_s3` or `azure`) OR the cloud site name (i.e. `philz-site`). If using a different backend like AWS or Azure, we always only use the type name specified in Federation.
Example routes:
`/_/metrics/crr/all`                         # Gets all CRR metrics for all sites
`/_/metrics/crr/philz-site`             # Gets all CRR metrics for philz-site
`/_/metrics/crr/all/throughput`     # Gets only throughput metrics for all sites
`/_/metrics/crr/azure/backlog`     # Gets only backlog metrics for azure site
Please refer to the following discussion for …

rf: change metrics route paths

---

extensions/lifecycle/tasks/LifecycleTask.js
tests/unit/lifecycle/LifecycleTask.spec.js

Bucket tags should be included in the object tags but does
not have to all the objects tags.
For example:
If a bucket rule has no tags/prefixes, this rule should apply
to all objects in the bucket.
If a bucket rule has rule 'key1/value1', the object should
also have AT LEAST 'key1/value1'. The object tags can have
many tags in total, but must only guarantee any of those
tags matches the bucket tags to qualify for the lifecycle
rule defined on the bucket rule.

fix: Lifecycle bucket tagging vs object tagging

---

extensions/lifecycle/lifecycleConsumer/LifecycleConsumer.js
extensions/lifecycle/lifecycleConsumer/task.js
extensions/lifecycle/lifecycleProducer/LifecycleProducer.js
extensions/lifecycle/lifecycleProducer/task.js

Catch SIGTERM in producer and consumer processes and call close() functions.

properly shutdown lifecycle processes

---

extensions/replication/ReplicationQueuePopulator.js
tests/unit/replication/ReplicationQueuePopulator.spec.js

Metrics redis keys are prepended with site name for
multi-cloud. The site name was not correctly targeted.

bf: fix metrics redis key site names

---

docker-entrypoint.sh

Fixes setting the replicaset through an env variable, otherwise fails with
```
"mongodb" is not allowed
```

Fix mongo replicaset setting

---

extensions/replication/constants.js
lib/api/BackbeatAPI.js
lib/api/BackbeatRequest.js
lib/api/BackbeatServer.js
lib/api/routes.js
tests/functional/api/BackbeatServer.js
tests/functional/utils/makePOSTRequest.js

Add the CRR retry routes. 🙌
This is the first PR of the retry feature. See the corresponding [design doc](https://github.com/scality/backbeat/blob/9dee4ca7b282c0a38bfaeeaa3a9a7ed11f0706e6/docs/replication-retry.md.) for further details.
🔜PR to push object metadata to kafka topics to actually do the retry actions.
Thanks!

FT: Add failure retry routes

---

tests/unit/lifecycle/LifecycleTask.spec.js

Most aws prefix examples show use of "/". Prefix tests, when filtering,
should filter based on the object key vs prefix defined in a bucket rule.

fix: improve lifecycle prefix unit test

---

tests/functional/api/BackbeatServer.js

Flakiness seen on this CI build:
https://circleci.com/gh/scality/backbeat/3180
For now, increasing timeouts and will need to observe

bf: fix flaky metrics tests

---

eve/main.yml
eve/workers/unit_and_feature_tests/backbeat_packages.list
eve/workers/unit_and_feature_tests/buildbot_worker_packages.list
eve/workers/unit_and_feature_tests/run_server_tests.bash
eve/workers/unit_and_feature_tests/supervisor/buildbot_worker.conf

The metrics api tests were not being run on eve since they were separated from the functional tests script

fix: run metrics api tests in eve

---

tests/unit/api/BackbeatAPI.spec.js
tests/unit/api/BackbeatRequest.spec.js

Targeting `rel/7.4`, to be forward ported to beta and updated for the changes there (if any), then to be forward ported to master.

ft: add metrics unit tests for route checks

---

package.json

Same fix done for master branch on rel/7.4-beta.

fix node-rdkafka version to 2.2.0

---

extensions/lifecycle/tasks/LifecycleTask.js
tests/unit/lifecycle/LifecycleTask.spec.js

Addresses null versions from versioning suspended buckets
As a last resort, compare LastModified times. If these
match, default to always pushing versions first over
delete markers. This is a bug that will need to be
fixed.
Bug tracking: S3C-1418
As known and requiring a fix

bf: handle null case versions

---

conf/Config.js

Adds support for configuring scality RING as aws_s3 locations.

Add RING/Ceph as aws_s3

---

extensions/replication/tasks/MultipleBackendTask.js
extensions/replication/utils/ObjectQueueEntry.js
tests/unit/replication/QueueEntry.spec.js

Sets the source bucket (instead of the destination bucket) as the bucket name when replicating to a public cloud. This allows S3's multiple backend to prefix the key properly when a location constraint has `bucketMatch` set to `false`. For example, the bucket name will be passed as context to S3's multiple backend here: https://github.com/scality/S3/blob/master/lib/routes/routeBackbeat.js#L352.

bf: ZENKO-252 Use source bucket for multiple backend replication

---

extensions/replication/replicationStatusProcessor/ReplicationStatusProcessor.js

Now that we have a single replication status processor so that operations occur sequentially, the `replicationInfo` backends may contain a 'FAILED' status from a previous operation. This change ensures that the failure hash field is set only once.
I will aim to get https://github.com/scality/Integration/pull/660 merged to avoid this kind of unexpected problem going forward.

bf: ZENKO-147 Check site when setting failed hash

---

extensions/lifecycle/tasks/LifecycleTask.js
tests/functional/lifecycle/LifecycleTask.js

A change was added to MPU params to guarantee that if the bucket entry contains `keyMarker`, an `uploadIdMarker` must be there, and vice versa.
Change added on L#922

ft: LifecycleTask tests for AbortMPU

---

conf/Config.js
lib/BackbeatConsumer.js
lib/api/BackbeatAPI.js
lib/api/BackbeatServer.js
lib/clients/monitoringHandler.js
lib/queuePopulator/QueuePopulatorExtension.js
package.json

[Corresponding route request in Arsenal](https://github.com/scality/Arsenal/pull/478)
- crr_number_of_sites: CRR number of sites
- crr_number_of_bytes: The number of CRR bytes completed by backbeat
- crr_number_of_bytes: The number of CRR bytes requested to be replicated
- crr_number_of_operations_completed: The number of CRR operations completed by backbeat
- crr_number_of_operations: The number of CRR operations requested(queued)
- nodejs_version_info Node.js: version info
- nodejs_heap_space_size_available_bytes: Process heap space size available from node.js in bytes
- nodejs_heap_size_total_bytes: Process heap size from node.js in bytes
- nodejs_heap_size_used_bytes: Process heap size used from node.js in bytes
- nodejs_external_memory_bytes: Nodejs external memory size in bytes
- …

Zenko-21: FT: CRR Metrics for backbeat

---

conf/config.joi.js
lib/queuePopulator/QueuePopulator.js

We need only and exactly one queue populator processing the mongo log,
but we have 10 running in Federation deployments, so one has to be
picked and failover to another when the active one fails.
This can be implemented the same way we did for raft session log
consumption, with help from zookeeper watchers (ProvisionDispatcher),
but instead of having 8 raft sessions to consume from, we only have
one mongo log.
Kubernetes deployments don't need this, so an option
"subscribeToLogSourceDispatcher" has been added, set to true in
Federation deployments only.

bf: zk dispatcher for mongo log

---

lib/api/BackbeatServer.js

All routes had preliminary checks made. One of these checks
were to check if conditions were ok. This check defeats the
purpose of a healthcheck, so the check needs to be eased for
healthcheck routes only

bf: allow healthchecks even if clients not ok

---

lib/BackbeatProducer.js
lib/queuePopulator/QueuePopulator.js

When Kafka is unavailable, the backbeat queue populator will hang and not connect to it even if it becomes available later on. These changes will make the backbeat queue populator throw an exception if it's unable to connect to Kafka after a certain amount of time.
In an orchestrated environment, the orchestration tool can recognize this crash and restart the failed container, thus allowing it to try to connect again to Kafka (which might be available later on).

bf: crash when unable to connect with kafka

---

extensions/replication/ReplicationConfigValidator.js
extensions/replication/replicationStatusProcessor/ReplicationStatusProcessor.js

Allow a configurable value to disable tracking CRR failures. 🚀

ft: ZENKO-147 Make CRR retry configurable

---

extensions/lifecycle/tasks/LifecycleObjectTask.js
extensions/lifecycle/tasks/LifecycleTask.js
extensions/replication/tasks/MultipleBackendTask.js
extensions/replication/tasks/ReplicateObject.js
extensions/replication/tasks/UpdateReplicationStatus.js
lib/clients/utils.js
lib/credentials/AccountCredentials.js

Some small refactors to prepare backbeat garbage collector implementation
-   rf: ZENKO-143 move attachReqUids() helper
Move attachReqUids() helper to lib/client/utils.js. This to done to
share the simple but useful logic across extensions.
-   rf: ZENKO-143 add helper getAccountCredentials()
Move account-credentials gathering in a single getAccountCredentials()
helper in AccountCredentials.js, instead of having to check the type
of authentication ('account' or 'service') and create the class
accordingly.

share helpers for gc

---

conf/config.json
extensions/replication/ReplicationConfigValidator.js
extensions/replication/failedCRR/FailedCRRConsumer.js
extensions/replication/failedCRR/FailedCRRProducer.js
extensions/replication/replicationStatusProcessor/ReplicationStatusProcessor.js
lib/queuePopulator/QueuePopulator.js
tests/config.json

Decouple logic around making calls to Redis and updating object metadata. Allows for usage of `ioredis`'s offline queue during cases where the connection to Redis is faulty. To that end, this PR alters the retry feature to do the following:
* Push failed entries to a kafka "retry" topic.
* Set Redis keys during processing of "retry" kafka entry.
Depends on https://github.com/scality/Federation/pull/1514 for creating the topic.

ft: S3C-1398 Use retry CRR topic

---

extensions/lifecycle/conductor/LifecycleConductor.js

Disable zookeeper provisioning for lifecycle conductors, as kubernetes is able to spawn the required number of instances (i.e. 1) and respawn on another machine whenever one goes down. The zookeeper provisioning was used for about the same purpose.

bf: ZENKO-408 no zookeeper provisioning for conductor

---

extensions/lifecycle/tasks/LifecycleTask.js
tests/unit/lifecycle/LifecycleTask.spec.js

From Error logs:
`TypeError: Cannot read property 'ExpiredObjectDeleteMarker' of undefined`

bf: check if Expiration rule exists before EODM

---

lib/api/BackbeatAPI.js
lib/api/BackbeatServer.js

Some changes are not reflected in this forward port because they have since migrated to Arsenal. 🛩

FWD: rel/7.4 to z/1.0
