- extensions/replication/queueProcessor/QueueProcessor.js
- extensions/replication/utils/QueueEntry.js
Depends on
~~-  #13~~
~~https://github.com/scality/Vault/pull/757~~
> FT: S3C-350 Use roles to lookup canonicalId

- README.md
> Docs/update README.md

- extensions/replication/queuePopulator/QueuePopulator.js
regression introduced in PR https://github.com/scality/backbeat/pull/27
> bf: fix name of queue populator logger variable

- lib/provisioning/ProvisionDispatcher.js
- tests/functional/ProvisionDispatcher.spec.js
Support raft ID auto provisioning with zookeeper watchers.
Replaces https://github.com/scality/backbeat/pull/22
> raft session provisioning

- extensions/replication/queuePopulator/BucketFileLogReader.js
- extensions/replication/queuePopulator/QueuePopulator.js
- extensions/replication/queuePopulator/task.js
- extensions/replication/queueProcessor/QueueProcessor.js
- extensions/replication/queueProcessor/task.js
- lib/BackbeatConsumer.js
- lib/BackbeatProducer.js
- lib/provisioning/ProvisionDispatcher.js
- tests/behavior/extensions/replication/queuePopulator.js
- tests/functional/BackbeatConsumer.js
- tests/functional/BackbeatProducer.js
- tests/functional/ProvisionDispatcher.spec.js
- tests/functional/replication/queueProcessor.js
Adapt backbeat to recent werelogs API changes, solving the issue of misconfiguration of the logging system.
> S3C-703 update werelogs config handling

- conf/config.joi.js
- lib/config/configItems.joi.js
This updates the zookeeper validation to a simple string check. This can be
revisited in the future with a more elaborate check.
> bf: update zookeeper config validation

- extensions/replication/queueProcessor/QueueProcessor.js
- tests/functional/replication/queueProcessor.js
don't update source metadata, just log and skip the entry
> bf: handle 404 error from source gracefully

- bin/setupReplication.js
Fix parsing of option flags.
Handle undefined profile option calls.
Fix validation of command used and options length.
> bf: Fix breaking commander use

- credentials/CredentialsManager.js
- extensions/replication/queueProcessor/QueueProcessor.js
- tests/functional/replication/queueProcessor.js
use bootstrapList with RoundRobin to select hosts
> target hosts failover

- extensions/replication/utils/QueueEntry.js
- lib/clients/backbeat-2017-07-01.api.json
Depends on https://github.com/scality/S3/pull/874.
> FT: Use key and dataStoreName returned from putData

- extensions/replication/queueProcessor/QueueProcessor.js
Make sure all logs have the origin peer of the error when applicable,
rename the attribute from 'origin' to 'peer' to avoid confusion,
instead, log 'source' or 'target' in the 'origin' attribute.
> cleanup: log error peer in 'peer' log attribute

- extensions/replication/queueProcessor/QueueProcessor.js
Restore graceful handling when an entry's location info does not have the
dataStoreETag property.
> bf: don't crash if dataStoreETag missing

- bin/replication.js
Note: Added change to require source and destination profiles on cli as well
> bf: Edit error logs, destination host

- extensions/replication/queuePopulator/BucketFileLogReader.js
Depends on https://github.com/scality/backbeat/pull/37.
> FIX: Set log consumer for BucketFileLogReader

- credentials/CredentialsManager.js
- extensions/replication/queuePopulator/BucketFileLogReader.js
- extensions/replication/queuePopulator/LogReader.js
- extensions/replication/queuePopulator/QueuePopulator.js
- extensions/replication/queuePopulator/RaftLogReader.js
- extensions/replication/queuePopulator/task.js
- extensions/replication/queueProcessor/QueueProcessor.js
- extensions/replication/queueProcessor/task.js
- extensions/replication/utils/QueueEntry.js
- lib/provisioning/ProvisionDispatcher.js
- tests/behavior/extensions/replication/queuePopulator.js
- tests/functional/ProvisionDispatcher.spec.js
- tests/functional/replication/queueProcessor.js
I tried to separate my commits by each type of eslint change, so it might be easiest to view by each commit.
Let me know what you think, if we should add or remove certain rules. Current rules can be viewed:
https://github.com/scality/Guidelines/blob/chore/upgradeEslint/index.js
List of Eslint rules: https://eslint.org/docs/rules/
Note: Indent fixes were mainly done by the linter --fix command
Note: Will squash commits after making any changes based on peoples' feedback
> Chore: upgrade eslint

- bin/queuePopulator.js
A regression introduced with abd4c7b0 disables the code that prevents
running multiple concurrent batches (when the previous batch is still
in progress). Fix the regression by reverting the relevant code.
Note: this regression can cause assert to be raised in generic queue
populator PR.
> bf: disallow parallel queue populator batches

- extensions/replication/ReplicationQueuePopulator.js
Ensure all updates to an object go to the same Kafka partition for AWS
support. Previously only updates to the same version were guaranteed to
end in the same partition.
Use QueueEntry class as a helper to get the master key from the
versioned key and use the former as the Kafka key. We also benefit
from more sanity checking.
> ft: object updates to same kafka partition

- extensions/replication/queueProcessor/QueueProcessorTask.js
Spawn a new request logger for each part of an MPU, so that it does
not clutter logs when dumping and consume a lot of CPU. Keep the
parent ID in the logger to link to whole object logs.
Also log the part info when relevant.
> bf: request logger for individual MPU parts

- bin/replication.js
- extensions/replication/queueProcessor/QueueProcessor.js
- extensions/replication/utils/SetupReplication.js
Allow omission of a cloud server site with
that includes the servers property
> FIX: Support multiple backend configuration

- lib/config/configItems.joi.js
Allow a default field in a replication endpoint object.
> FT: Add default field to replication endpoint

- conf/config.json
- extensions/replication/ReplicationQueuePopulator.js
- extensions/replication/queueProcessor/QueueProcessor.js
- extensions/replication/utils/QueueEntry.js
- lib/queuePopulator/LogReader.js
needs to be merged with https://github.com/scality/Zenko/pull/28
tested with orbit that replication still works
> HACK to have one populator

- conf/Config.js
- conf/config.joi.js
- extensions/index.js
- extensions/replication/ReplicationConfigValidator.js
- extensions/replication/index.js
- lib/queuePopulator/QueuePopulator.js
ft: manage extensions configuration
Each extension is now responsible to manage its config stored in the
global config.json, through a custom configValidator function.
Built on top of https://github.com/scality/backbeat/pull/98
> extension config management

- conf/Config.js
- conf/config.joi.js
- conf/config.json
separating out metrics configs
> ft: include all metrics configs

- Dockerfile
- bin/queuePopulator.js
- conf/config.joi.js
- conf/config.json
- docker-entrypoint.sh
- extensions/replication/ReplicationConfigValidator.js
- extensions/replication/queueProcessor/QueueProcessor.js
- extensions/replication/queueProcessor/task.js
- lib/BackbeatConsumer.js
- lib/credentials/AccountCredentials.js
- lib/management.js
- lib/queuePopulator/BucketFileLogReader.js
- lib/queuePopulator/LogReader.js
- lib/queuePopulator/MongoLogReader.js
- lib/queuePopulator/QueuePopulator.js
- lib/queuePopulator/RaftLogReader.js
- tests/config.json
JIRA ticket: https://scality.atlassian.net/browse/ZENKO-15
https://github.com/scality/Arsenal/pull/425 needs to be merged first.
> Ft/ MongoDB oplogs

- docker-entrypoint.sh
New vars to define mongodb host string and database
> Update entry point for configurable mongodb vars

- tests/config.json
- tests/functional/api/BackbeatServer.js
cherry-pick of PR #204 to rel/7.4-beta
> fix: metrics test flakiness

- extensions/lifecycle/LifecycleQueuePopulator.js
- extensions/lifecycle/conductor/LifecycleConductor.js
- tests/behavior/queuePopulator.js
- tests/functional/lifecycle/LifecycleConductor.spec.js
add bucket uid to lifecycle zookeeper nodes
> store bucket uid in zookeeper

- docs/lifecycle.md
First version of the lifecycle detailed design, please review and comment or suggest changes.
> doc: lifecycle design doc

- Dockerfile
Makes sure the long-ish modules installation is not done at each source file change, makes build and push a lot faster
> Speed up rebuilding docker image

- docs/lifecycle.md
- extensions/lifecycle/conductor/LifecycleConductor.js
- extensions/lifecycle/lifecycleProducer/LifecycleProducer.js
- tests/unit/lifecycle/LifecycleTask.spec.js
backport of the following PRs already merged to master into rel/7.4-beta:
- https://github.com/scality/backbeat/pull/166
- https://github.com/scality/backbeat/pull/230
- https://github.com/scality/backbeat/pull/223
> Backport/7.4 beta/lifecycle

- circle.yml
- docs/healthcheck.md
- docs/metrics.md
- eve/main.yml
- eve/workers/unit_and_feature_tests/backbeat_packages.list
- eve/workers/unit_and_feature_tests/buildbot_worker_packages.list
- eve/workers/unit_and_feature_tests/run_server_tests.bash
- eve/workers/unit_and_feature_tests/supervisor/buildbot_worker.conf
- extensions/lifecycle/tasks/LifecycleTask.js
- package.json
- tests/functional/api/BackbeatServer.js
- tests/functional/lifecycle/LifecycleTask.js
- tests/unit/api/BackbeatAPI.spec.js
- tests/unit/api/BackbeatRequest.spec.js
- tests/unit/lifecycle/LifecycleTask.spec.js
also added: dce8574e5e09b6f4e7f2abbd27cda4d8e408f2e1
> Fwdport: 7.4-beta to master

- extensions/lifecycle/tasks/LifecycleTask.js
- tests/functional/lifecycle/LifecycleTask.js
- tests/unit/lifecycle/LifecycleTask.spec.js
First commit is a small refactor, renaming certain methods and splitting certain methods to use more helper methods and spot reuse.
Second commit addresses the lifecycle `IsLatest` versions, and includes `ExpiredObjectDeleteMarker` rule
> ft: S3C-1397 support Lifecycle IsLatest version

- extensions/replication/tasks/ReplicateObject.js
> bf: ZENKO-272 Undefined error logger

- lib/api/BackbeatAPI.js
- package.json
- tests/unit/api/BackbeatAPI.spec.js
Also see https://github.com/scality/Arsenal/pull/475
> bf: S3C-1427 average throughput using expired intervals

- lib/api/BackbeatAPI.js
- lib/api/BackbeatRequest.js
- lib/api/BackbeatServer.js
- tests/functional/api/BackbeatServer.js
* Add pagination
* Model closer to getObjectVersions API
> rf: ZENKO-147 Refactor retry CRR API

- lib/api/BackbeatAPI.js
> ft: ZENKO-147 delete hash field on retry

- extensions/lifecycle/LifecycleQueuePopulator.js
Mongo log have a different structure than raft logs, for this reason
we adapt the queue populator lifecycle extension filter to correctly
process bucket updates from mongo.
> bf: ZENKO-343 adapt lifecycle qp extension for mongo

- docker-entrypoint.sh
This is needed for the lifecycle helm chart
> ft: ZENKO-300 Add environment config for lifecycle
